CREATE DATABASE IF NOT EXISTS `eGovernment`;

USE `eGovernment`;

CREATE TABLE IF NOT EXISTS `user` (
	`id` INT AUTO_INCREMENT NOT NULL,
	`surname` VARCHAR(50) NOT NULL,
	`name` VARCHAR (50) NOT NULL,
	`password` VARCHAR(50) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS `menu` (
	`id` INT AUTO_INCREMENT NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`level` INT(1) NOT NULL
);
